version: "3.8"
services:
  fastapi:
    build: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    networks:
      - qdrant_network

networks:
  qdrant_network:
    external: true
