[tool.black]
line-length = 140
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 140
select = ["E", "F", "W", "C", "N", "Q", "B", "I"]
exclude = ["venv", "build", "dist"]

# Optional: Per-file ignores
#[tool.ruff.per-file-ignores]
# "tests/*" = ["F401"]
